Fix PyPy 2.6.1 issue.
Travis CI discovered that PyPy in version 2.6.1 apparently lacks the
ENOTSUP variable.  This commit defines the variable if it does not exist
already.  The exact test error was:

  ============================= test session starts ==============================

  platform linux2 -- Python 2.7.10[pypy-2.6.1-final], pytest-2.8.5, py-1.4.31, pluggy-0.3.1

  rootdir: /home/travis/build/NullHypothesis/exitmap, inifile:

  plugins: cov-2.2.1

  collected 8 items / 1 errors

  test/test_relayselector.py .

  test/test_stats.py .

  test/test_util.py ......

  ==================================== ERRORS ====================================

  ____________________ ERROR collecting test/test_torsocks.py ____________________

  test/test_torsocks.py:24: in <module>

      import torsocks

  src/torsocks.py:61: in <module>

      0x07: errno.ENOTSUP,      # Command not supported / protocol error

  E   AttributeError: 'module' object has no attribute 'ENOTSUP'